-- ============================================================
-- Property Manager — initial schema
-- Local Supabase migration.
-- ============================================================

-- ---------- properties: the thing that gets a pin on the map ----------
create table if not exists properties (
  id            bigint generated by default as identity primary key,
  address       text not null,
  display_name  text,
  latitude      double precision,   -- set by the in-app map picker (NOT typed by hand)
  longitude     double precision,
  image_url     text,               -- building photo shown on the comp card
  created_at    timestamptz default now()
);

-- ---------- leases: lease comps ----------
create table if not exists leases (
  id                bigint generated by default as identity primary key,
  property_id       bigint references properties(id) on delete cascade,
  tenant            text,
  name              text,
  rank_ytd          integer,
  signed_date       date,
  sf                integer,
  floors            text,
  term_months       integer,
  lease_type        text,           -- Direct / Sublease
  yr1_rent_psf      numeric,
  escalation_pct    numeric,
  free_rent_months  integer,
  ti_psf            numeric,
  deal_type         text,           -- Expansion / Renewal / Relocation / New Lease / Extension
  notes             text,           -- original source text (provenance)
  created_at        timestamptz default now()
);

-- ---------- transactions: sale comps ----------
create table if not exists transactions (
  id            bigint generated by default as identity primary key,
  property_id   bigint references properties(id) on delete cascade,
  name          text,
  status        text check (status in ('on_market','closed')),
  sub_status    text,               -- Marketing / Bidding / Awarded
  as_of_date    date,
  sf            integer,
  pct_leased    numeric,
  cap_low       numeric, cap_high numeric,
  psf_low       integer, psf_high integer,
  price_low     bigint,  price_high bigint,
  buyer         text,               -- NULL when TBD / Confidential
  seller        text,
  notes         text,
  created_at    timestamptz default now()
);

-- ---------- indexes for dashboard filters / timeline ----------
create index if not exists idx_props_geo   on properties(latitude, longitude);
create index if not exists idx_ls_signed   on leases(signed_date);
create index if not exists idx_ls_type     on leases(lease_type);
create index if not exists idx_ls_term     on leases(term_months);
create index if not exists idx_tx_status   on transactions(status);
create index if not exists idx_tx_asof     on transactions(as_of_date);

-- ---------- analytics views (feed the stat panels & timeline) ----------
create or replace view v_lease_stats as
select count(*) filter (where yr1_rent_psf is not null)     as rent_n,
       max(yr1_rent_psf)                                     as rent_high,
       min(yr1_rent_psf)                                     as rent_low,
       round(avg(yr1_rent_psf), 2)                           as rent_avg,
       round((percentile_cont(0.5) within group (order by yr1_rent_psf))::numeric, 2) as rent_median,
       max(sf) as sf_max, min(sf) as sf_min, sum(sf) as sf_total,
       round((percentile_cont(0.5) within group (order by sf))::numeric, 0) as sf_median
from leases;

create or replace view v_leasing_by_month as
select date_trunc('month', signed_date)::date as month,
       count(*) as deal_count, sum(sf) as total_sf,
       round(avg(yr1_rent_psf), 2) as avg_rent
from leases where signed_date is not null
group by 1 order by 1;

-- lease term buckets for the timeline categories
create or replace view v_lease_term_buckets as
select case
         when term_months >= 120 then 'Long (10y+)'
         when term_months >= 60  then 'Mid (5-10y)'
         when term_months is null then 'Unknown'
         else 'Short (<5y)'
       end as term_bucket,
       count(*) as deal_count
from leases group by 1;

-- ============================================================
-- Row Level Security
-- Local dev: public read + permissive write so the CRUD app works
-- with the anon key immediately. TIGHTEN before any real deploy
-- (gate writes behind authenticated admins).
-- ============================================================
alter table properties   enable row level security;
alter table leases       enable row level security;
alter table transactions enable row level security;

create policy "read properties"  on properties   for select using (true);
create policy "read leases"       on leases       for select using (true);
create policy "read transactions" on transactions for select using (true);

create policy "write properties"  on properties   for all using (true) with check (true);
create policy "write leases"       on leases       for all using (true) with check (true);
create policy "write transactions" on transactions for all using (true) with check (true);
